### ISSUE TITLE
Preliminary Investigation Report

### ISSUE THREAD

**Issue by alilinares** [kalapyha/solitaire-group-9#18]
## Part I: Preliminary Investigation

Part I of this assignment will require you to complete a preliminary investigative report. This will serve as an initial introduction to the preliminary investigation required in order to accurately estimate and define feature scope. A preliminary investigation is typically performed after the initial feature outline and definition have been done by management, product owners, support and marketing.
Please consider the following scenario:

`You will be using the current project (Identified in Project Outline) as a basis for completing this first part of the assignment. In order to complete Part I, you will be working as though you have been asked to implement an additional game, <GAME> in order to complete the contract. Your team is already at capacity and cannot take on any additional work without needing to abandon or delay your current project. You are presented with the option of hiring outside help to complete this project.`

You are tasked with conducting a **preliminary investigation report.** You will need to use the terms and concepts you’ve learned thus far around AGILE to outline what the process for the preliminary investigation report might look like. 

You will need to provide the following items as part of your preliminary investigation report:

- [ ] #19
- [x] #20
- [x] #21
- [ ] #22
- [ ] #23
- [x] #24
- [x] #25
- [x] #26
- [ ] #27

## Part 2
Part II: Demo Requirements
Use the module content describing the concept and importance of Demos to complete the following presentation.
Consider the following when presenting your Prototype:

- [ ] #28
- [ ] Ensure that your Demo shows what you have completed up to this point. 
- [ ] Ensure that all High Priority items identified in the Project Outline are included in the presentation
- [ ] The presentation should avoid simply listing the work that has been completed.
    - [ ] Instead, you should show actual functionality. 
    - [ ] This is also a great opportunity to highlight areas of the functionality that can be used to build excitement for key stakeholders.
- [ ] Keep in mind that this Demo is a good time for you and your team to explain and demonstrate any workarounds implemented and/or potential issues.  
    - [ ] Unclear requirements are outlined at the same time.
- [ ] The Demo should be kept short and concise in order to maintain engagement. 
    - [ ] our Demo should be a maximum of 5 minutes
